image:
  repository: ea-ainu-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  PORT: 8080
  GIN_MODE: release

secrets:
  DB_URL: mongodb://mongodb.ea-platform.svc.cluster.local

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 30s

pdb:
  maxUnavailable: "50%"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

service:
  type: ClusterIP
  port: 8080

networkPolicy:
  enabled: true  # Enforce in cluster network traffic controlls for the deployement

ingress:
  enabled: true
  className: "kong"
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: global-jwt-auth, global-cors 
  hosts:
    - host: 
      paths:
        - path: /ainu-manager
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
