image:
  repository: localhost:5000/ea-job-engine
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  AGENT_MANAGER_URL: http://ea-agent-manager.ea-platform.svc.cluster.local:8080/api/v1/agents/

secrets:
 # DB_URL: mongodb://user:password@mongodb.brand-backend.svc.cluster.local

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

pdb:
  maxUnavailable: "50%"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: brand-backend.erulabs.ai
      paths:
        - path: /
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
