---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ea-gateway
  namespace: ea-platform
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "*.erulabs.local"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    hostname: "*.erulabs.local"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: self-signed-cert
          namespace: ea-platform
    allowedRoutes:
      namespaces:
        from: All