---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: front
  namespace: ea-platform
spec:
  parentRefs:
  - name: ea-gateway
    namespace: ea-platform
  hostnames: ["ea.erulabs.local"]
  rules:
  - matches:
     - path:
        type: PathPrefix
        value: / 
    backendRefs:
      - name: ea-front
        port: 8080
