version: "3.8"

services:
  # # Service 1: eru-labs-brand-backend
  # eru-labs-brand-backend:
  #   build:
  #     context: ./brand-backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8080" 
  #   container_name: eru-labs-brand-backend

  # # Service 2: eru-labs-brand-frontend
  # eru-labs-brand-frontend:
  #   build:
  #     context: ./brand-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080" 
  #   container_name: eru-labs-brand-frontend

  # # Service 3: ea-frontend
  # ea-frontend:
  #   build:
  #     context: ./ea-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8080" 
  #   container_name: ea-frontend

  # Service 4: mongodb
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "8083:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data: