version: "3.8"

services:
  # Service 1: eru-labs-brand-backend
  eru-labs-brand-backend:
    build:
      context: ./brand-www/backend
      dockerfile: Dockerfile
    ports:
      - "8082:8080" 
    container_name: eru-labs-brand-backend

  # Service 2: eru-labs-brand-frontend
  eru-labs-brand-frontend:
    build:
      context: ./brand-www/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    container_name: eru-labs-brand-frontend

  # Service 2: ea-frontend
  ea-frontend:
    build:
      context: ./ea-platform/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080" 
    container_name: ea-frontend