apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: ea-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ea-agent-manager
  policyTypes:
    - Ingress
    - Egress
