{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ea-ainu-operator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["ea.erulabs.ai"]
    resources: ["agentjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["ea.erulabs.ai"]
    resources: ["agentjobs/status"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ea-ainu-operator-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ea-ainu-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: ea-ainu-operator-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
