apiVersion: v1
kind: Secret
metadata:
  name: ea-ainu-manager-secrets
  labels:
    app: {{ include "ea-ainu-manager.name" . }}
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}