{
 "title": "ea logs overview",
 "time": { "from": "2025-02-25T11:26:27.846Z", "to": "2025-02-25T23:26:27.846Z" },
 "templating": {
  "list": [
   {
    "name": "apis",
    "query": "ea-agent-manager, ea-ainu-manager, ea-job-api"
   }
  ]
 },
 "panels": [
  { "title": "$apis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "apis" },
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"$apis\"} !~ `/metrics` |= `[GIN]` | pattern `[<_>] <date> - <time> | <response_code> |     <response_time> |     <ip> | <http_method>      \"<request>\"` | response_code =~ `200|201|202` [$__auto]))",
     "legendFormat": "success"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"$apis\"} !~ `/metrics` |= `[GIN]` | pattern `[<_>] <date> - <time> | <response_code> |     <response_time> |     <ip> | <http_method>      \"<request>\"` | response_code =~ `401|403` [$__auto]))",
     "legendFormat": "unauthorized"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"$apis\"} !~ `/metrics` |= `[GIN]` | pattern `[<_>] <date> - <time> | <response_code> |     <response_time> |     <ip> | <http_method>      \"<request>\"` | response_code =~ `400` [$__auto]))",
     "legendFormat": "bad request"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"$apis\"} !~ `/metrics` |= `[GIN]` | pattern `[<_>] <date> - <time> | <response_code> |     <response_time> |     <ip> | <http_method>      \"<request>\"` | response_code =~ `5` [$__auto]))",
     "legendFormat": "server error"
    }
   ]
  },
  {
   "title": "Gin Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"$apis\"} !~ `/metrics` |= `[GIN]` | pattern `[<_>] <date> - <time> | <response_code> |     <response_time> |     <ip> | <http_method>      \"<request>\"`",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Slog Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"$apis\"} !~ `/metrics` != `[GIN]` | json",
     "legendFormat": "success"
    }
   ]
  }
 ]
}