{
 "title": "Compliance and Security Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Trivy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Compliance Passing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(title) (trivy_cluster_compliance{status=\"Pass\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Cluster Compliance Failing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(title) (trivy_cluster_compliance{status=\"Fail\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Eru Labs Vulns",
   "type": "stat",
   "description": "Vulns detected by Trivy for the ea-platform and eru-labs-brand namespaces",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"ea-platform|eru-labs-brand\", severity=\"Critical\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"ea-platform|eru-labs-brand\", severity=\"High\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"ea-platform|eru-labs-brand\", severity=\"Medium\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"ea-platform|eru-labs-brand\", severity=\"Low\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "monitoring Vulns",
   "type": "stat",
   "description": "Vulns detected by Trivy for the monitoring namespace",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"monitoring\", severity=\"Critical\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"monitoring\", severity=\"High\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"monitoring\", severity=\"Medium\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"monitoring\", severity=\"Low\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-system Vulns",
   "type": "stat",
   "description": "Vulns detected by Trivy for the kube-system namespace",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"kube-system\", severity=\"Critical\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"kube-system\", severity=\"High\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"kube-system\", severity=\"Medium\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(severity) (trivy_vulnerability_id{namespace=~\"kube-system\", severity=\"Low\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trivy Vulns Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(resource_name, severity, vuln_id, vuln_score, vuln_title, installed_version, fixed_version, namespace) (trivy_vulnerability_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Falco", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Events Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"falco\"} | json | priority = \"Critical\" [5m]))\n",
     "legendFormat": "Critical"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"falco\"} | json | priority = \"Warning\" [5m]))\n",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "SCAP Events Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "sum(falcosecurity_scap_n_evts_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Falco Rule Matches by Name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 30 },
   "targets": [
    {
     "expr": "sum by(rule_name) (falcosecurity_falco_rules_matches_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Events",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"falco\"} | json | priority = `Critical`"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"falco\"} | json | priority = `Warning`"
    }
   ]
  }
 ]
}