apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ea-job-engine.fullname" . }}-pdb
  labels:
    app: {{ include "ea-job-engine.name" . }}
spec:
  minAvailable: 
    {{- if .Values.pdb.minAvailable }}
    {{ .Values.pdb.minAvailable }}
    {{- else }}
    null
    {{- end }}
  maxUnavailable:
    {{- if .Values.pdb.maxUnavailable }}
    {{ .Values.pdb.maxUnavailable }}
    {{- else }}
    null
    {{- end }}
  selector:
    matchLabels:
      {{- include "ea-job-engine.selectorLabels" . | nindent 6 }}
