{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ea-credentials-manager-role
  namespace: {{ .Release.Namespace }}
rules:
  # 🔹 Allow creating, reading, updating, and deleting Kubernetes Secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ea-credentials-manager-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ea-credentials-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: ea-credentials-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
