{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ea-job-utils.fullname" . }}-network-policy-allow
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ea-job-utils
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              job-group: ea-agent-executor-job
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system      
{{- end }}
