{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ea-job-executor-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ea-job-executor-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ea-job-executor-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: ea-job-executor-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
