image:
  repository: ea-job-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  AGENT_MANAGER_URL: http://ea-agent-manager.ea-platform.svc.cluster.local:8080/api/v1/agents/
  GIN_MODE: release

secrets:
 # DB_URL: mongodb://user:password@mongodb.brand-backend.svc.cluster.local

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 30s

pdb:
  maxUnavailable: "50%"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ea-job-api
  automount: true
  annotations: {}

rbac:
  enabled: true

podAnnotations: {}

podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "kong"
  annotations:
    konghq.com/strip-path: 'true'
  hosts:
    - host: 
      paths:
        - path: /job-api
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
