image:
  repository: ea-front
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  PORT: 8080

secrets:
  DATABASE_URL: "postgresql://admin:super-password@postgresql:5432/ea"
  JWT_SECRET: "super-secret"

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 30s

pdb:
  maxUnavailable: "50%"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

rbac:
  enabled: true

podAnnotations: {}

podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "kong"
  annotations: {}
  hosts:
    - host: ea.erulabs.local
      paths:
        - path: /
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

initContainers:
  - name: migrate
    image: ea-front:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'npx prisma migrate deploy']
    envFrom:
      - secretRef:
          name: ea-front-secrets