{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ea-agent-manager-route
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  - {{ .Values.gateway.host }}
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: {{ .Values.gateway.pathPrefix }}
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            replacePrefixMatch: /
            type: ReplacePrefixMatch
    backendRefs:
    - name: {{ include "ea-agent-manager.fullname" $ }}
      port: {{ $.Values.service.port }}
{{- end -}}