server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  extraArgs:
    web.enable-remote-write-receiver: null

  scrape_configs:
    - job_name: "alloy-metrics"
      static_configs:
        - targets: ["alloy.monitoring.svc.cluster.local:12345"]  # Alloy Metrics Endpoint
