{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eafront-route
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  - {{ .Values.gateway.host }}
  rules:
  - backendRefs:
    - name: {{ include "ea-front.fullname" $ }}
      port: {{ $.Values.service.port }}
{{- end -}}