apiVersion: v1
kind: Secret
metadata:
  name: ea-front-secrets
  labels:
    app: {{ include "ea-front.name" . }}
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}