image:
  repository: ea-credentials-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  PORT: 8080
  GIN_MODE: release

secrets:
  # DB_URL: mongodb://mongodb.ea-platform.svc.cluster.local

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 30s

pdb:
  maxUnavailable: "50%"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

rbac:
  enabled: true

podAnnotations: {}

podLabels: 
 jwt: "true"

service:
  type: ClusterIP
  port: 8080

networkPolicy:
  enabled: true  # Enforce in cluster network traffic controlls for the deployement

gateway:
  enabled: true
  name: ea-gateway
  host: api.erulabs.local
  pathPrefix: /credentials-manager

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: credentiaals-manager.ea.erulabs.local
      paths: 
        - path: /
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/metrics
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
