name: Build & Push

on:
  push:
    paths:
      - 'ea-platform/ea-agent-manager/**' # Change this path to your app directory
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - id: 'gcp-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'sethvargo/oidc-auth-google-cloud@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/135550390903/locations/global/workloadIdentityPools/actions-pool/providers/github-provider'
        service_account: 'github-actions@eru-labs-dev-446616.iam.gserviceaccount.com'

    - id: 'docker-login'
      run: |-
        echo "${{ steps.gcp-auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev/eru-labs-dev-446616/eru-labs-images

    - name: Build & Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/eru-labs-dev-446616/eru-labs-images/ea-agent-manager:latest ea-platform/ea-agent-manager
        docker push us-central1-docker.pkg.dev/eru-labs-dev-446616/eru-labs-images/ea-agent-manager:latest