name: Build & Push

on:
  push:
    # paths:
    #   - 'ea-platform/ea-agent-manager/**' # Change this path to your app directory
    # branches:
    #   - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        name: authenticate to google cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/135550390903/locations/global/workloadIdentityPools/actions-pool/providers/github-provider'
          service_account: 'github-actions@eru-labs-dev-446616.iam.gserviceaccount.com'

      - name: docker login
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             us-central1-docker.pkg.dev/eru-labs-dev-446616/eru-labs-images/ea-agent-manager:latest


